<?php

$keys = array (
  1 => 'telecom',
  2 => 'clavier',
  3 => 'scanner',
  4 => 'volant',
  5 => 'camera',
  6 => 'diodes',
  7 => 'imprimante',
  8 => 'mémoires',
  9 => 'navigation',
  10 =>'projecteur',
  11 =>'RV',
);

$keyimg[1] = 'tel/Tel-1982-Mobira_Talkman_FB.jpg';
$data[1] = array (
  array('date' => "1667", 'img'=> 'tel/Tel-1667-RobertHooke-ficelle_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1876", 'img'=> 'tel/Tel-1876-Emetteuraliquide_Graham_Bell_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1877", 'img'=> 'tel/Tel-1877-HandTelephone_G.Bell_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1880", 'img'=> 'tel/Tel-1880_Ader_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1892", 'img'=> 'tel/Tel-1892-Milde_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1907", 'img'=> 'tel/Tel-1907_Aboilard_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1910", 'img'=> 'tel/Tel-1910-Marty_mobileAOIP_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1924", 'img'=> 'tel/Tel-1924-PTT24_mobile_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1926", 'img'=> 'tel/Tel-1926-AlexanderGraham_Bell_Wikipedia_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1936", 'img'=> 'tel/Tel-1936-Motorola_MTS_FB.jpg',
        'title'=> '',
        'desc' => 'C\'est en 1936 que les ingénieur Alton Dickieson, HI Romnes D. Mitchell alors ingénieur d\'AT & T commença la conception du radio téléphone. Le premier appel d\'un radio téléphone fut émis en 1946, à St. Louis. Ce radio téléphone le MTS (Mobile Telephone System) fut conçu par Motorola, en collaboration avec le Bell System.<br/>Il faut attendre 1970, pour que Amos Joel E., Jr., un autre ingénieur de Bell Labs, mette au point un système pour permettre aux téléphones mobiles de se déplacer dans plusieurs cellules au cours d\'une même conversation sans perte de la conversation.'),
  array('date' => "1940", 'img'=> 'tel/Tel-1940-43ivoire_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1943", 'img'=> 'tel/Tel-1943-PupitreOperateur_Bakelite_CIT_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1950", 'img'=> 'tel/Tel-1950-Ericsson_Bakelite_Cadran_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1956", 'img'=> 'tel/Tel-1956-MTA_Ericcson_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1960", 'img'=> 'tel/Tel-1960-1990_filaire_cadran_Wikipedia_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1962", 'img'=> 'tel/Tel-1962-IMTS_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1965", 'img'=> 'tel/Tel-1965_MaxLaMenace_MaxwellSmart.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1975", 'img'=> 'tel/Tel-1975-filaire_clavier_FB.jpg',
        'title'=> 'T75',
        'desc' => 'Le poste Télic 1975, ou T75, est le premier poste téléphonique "électronique" français. Il est conçu et fabriqué à Strasbourg, dans l\'une des unités qui deviendra plus tard Alcatel. Ses innovations sont un design particulièrement proche des tendances de son époque (formes arrondies, couleur orange), la numérotation par clavier électronique en option (la version initiale ne proposait qu\'un cadran classique), et la possibilité d\'écoute amplifiée. A noter que cette fonction demande l\'installation de piles à l\'intérieur du poste. En effet, la consommation de son amplificateur est telle qu\'il est impossible de s\'alimenter directement sur le courant de la ligne téléphonique. Etant un modèle haut de gamme, sa diffusion sera relativement restreinte en raison de son coût. Le design de ce poste servira plus tard de base aux terminaux téléphoniques du système de réseau pour entreprise type T16.'),
  array('date' => "1982", 'img'=> 'tel/Tel-1982-Dynatact_Motorola_(source_LePost.fr)_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1982", 'img'=> 'tel/Tel-1982-Mobira_Talkman_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "2008", 'img'=> 'tel/Tel-2008-HologrammeCNN_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "2009", 'img'=> 'tel/Tel-2009-lg-montre-telephone.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "2010", 'img'=> 'tel/Tel-2010-PHILIPS_sansfil_CD1752B_Duo_FB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "2030", 'img'=> 'tel/Tel-2030-digitaltooth_f.4202_httpwww.petitpetitgamin.com.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "2030", 'img'=> 'tel/Tel-2030-iphone-hologram_FB.jpg',
        'title'=> '',
        'desc' => ''),
  #array('date' => "", 'img'=> 'tel/Tel-PopPhone_FB.jpg'),
  #array('date' => "", 'img'=> 'tel/Tel-portevoix_FB.jpg'),
  #array('date' => "", 'img'=> 'tel/Tel-PortORotaryRED-03-Lima_FB.jpg'),
  #array('date' => "", 'img'=> 'tel/Tel-PortORotaryRED_FB.jpg'),
  array('date' => "2101", 'img'=> 'tel/Tel-Star_Wars_hologram_FB.jpg',
        'title'=> '',
        'desc' => ''),
);

$keyimg[2] = 'key/5amarina-clavier-pliable-1.jpg';
$data[2] = array (
  array('date' => "1500", 'img'=> 'key/1calame3200av.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1920", 'img'=> 'key/2clavier_horton_premier1890.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1950", 'img'=> 'key/3machine-a-ecrire.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1995", 'img'=> 'key/4clavier.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1998", 'img'=> 'key/5amarina-clavier-pliable-1.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "2000", 'img'=> 'key/6clavier_nokey1.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "2010", 'img'=> 'key/7celluon-magic-cube.jpg',
        'title'=> '',
        'desc' => ''),
);


$keyimg[3] = 'scanner/08-Scanners.tambour.1990-WA.jpg';
$data[3] = array (
  array('date' => "1856", 'img'=> 'scanner/01-Pantelegraphe.1856-WA.jpg',
        'title'=> 'Le pantélégraphe',
        'desc' => 'Le pantélégraphe est un télégraphe autographique, il permet la transmission d\'une reproduction fidèle d\'un manuscrit, d\'un dessin, d\'un plan ou d\'un portrait. C\'est un invention de Giovanni Caselli.'),
  array('date' => "1908", 'img'=> 'scanner/02-Belinographe.1908-WA.jpg',
        'title'=> 'Le bélinographe',
        'desc' => 'Cette invention permet la transmission à distance de texte, de document, et surtout de photographie. À l\'origine, ila été utilisé pour transmettre l\'information sur une ligne télégraphique ou téléphonique.'),
  array('date' => "1920", 'img'=> 'scanner/03-Feldhellschreiber.1920-WA.jpg',
        'title'=> 'Le Feldhellschreiber ou Hellschreiber',
        'desc' => 'Il était à l\'origine un système d\'impression à distance de type fax inventé par Rudolf Hell. Cette technique de communication est désormais mise en œuvre logiciellement sur ordinateur par des radioamateurs.'),
  array('date' => "1943", 'img'=> 'scanner/04-Telefax.1943-WA.jpg',
        'title'=> 'Téléfax',
        'desc' => 'Un télécopieur ou téléfax est un appareil électronique qui convertit l\'image de documents en impulsions électriques pour les transmettre à un destinataire.'),
  array('date' => "1951", 'img'=> 'scanner/05-Lecteur-code-barres.1951-WA.jpg',
        'title'=> 'Lecteur de code-barres',
        'desc' => 'Un lecteur de code-barres est un appareil servant à lire les informations stockées sous la forme de codes-barres en utilisant des diodes électroluminescentes ou un laser. On l\'appelle aussi douchette ou scannette dans le cas de son utilisation courante.'),
  array('date' => "1980", 'img'=> 'scanner/06-Scanner.1980-WA.jpg',
        'title'=> 'Scanner ou numériseur de document',
        'desc' => 'Un scanner ou numériseur de document, est un périphérique informatique qui permet de transformer un document en une image numérique. Le document est soumis au balayage d\'un rayon lumineux ; un capteur transforme la lumière reçue en un signal électrique qui est transféré à l\'ordinateur, pour y être ensuite sauvegardé, traité ou analysé.'),
  array('date' => "1985", 'img'=> 'scanner/07-Scanner.Diapositives.1980-WA.jpg',
        'title'=> 'Scanners à diapositives',
        'desc' => 'Dans un scanneur à diapositive, la lumière est directe, elle traverse le document transparent, ce qui permet d\'obtenir une qualité chromatique et une résolution très importantes.'),
  array('date' => "1990", 'img'=> 'scanner/08-Scanners.tambour.1990-WA.jpg',
        'title'=> 'Scanners à tambour',
        'desc' => 'Les scanneurs à tambour offrent une résolution et une qualité colorimétrique sans égal, mais ils ne sont pas adaptés à tous les types de documents, ils doivent pouvoir s\'enrouler autour du cylindre et ne pas dépasser 1 mm d\'épaisseur.'),
  array('date' => "1990", 'img'=> 'scanner/09-Scanners.main.1990.jpg',
        'title'=> 'Scanners à main',
        'desc' => 'Avec un scanneur à la main l\'opérateur fait défiler l\'outil contre le document à scanner.'),
  array('date' => "1993", 'img'=> 'scanner/10-Scanners.tomodensitometrie.1993-WA.jpg',
        'title'=> 'Scanners de tomodensitométrie',
        'desc' => 'Il est un appareil qui travail avec un  technique d\'imagerie médicale qui consiste à mesurer l\'absorption des rayons X par les tissus puis, par traitement informatique, à numériser et enfin reconstruire des images 2D ou 3D des structures anatomiques.'),
  array('date' => "2010", 'img'=> 'scanner/11-Scanner.Corporel.2010-WA.jpg',
        'title'=> 'Scanner corporel à ondes millimétriques',
        'desc' => 'Un scanner corporel à ondes millimétriques est un type de scanner corporel destiné à assurer la sûreté dans les aéroports en permettant d\'inspecter les passagers et de détecter les objets interdits dissimulés sous les vêtements sans avoir recours à la fouille corporelle.'),
);

$keyimg[4] = 'volant/20110521143848675.jpg';
$data[4] = array (
  array('date' => "1769", 'img'=> 'volant/volant-1769-nicolas.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1850", 'img'=> 'volant/volant-Le_Xe_à_XVIIe_siècle.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1893", 'img'=> 'volant/volant-1893-Bretagne_esquisse.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1900", 'img'=> 'volant/20090720185413-279915467.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1910", 'img'=> 'volant/201005261403170909603.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1920", 'img'=> 'volant/201005261403076211151.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1950", 'img'=> 'volant/20110521143848675.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1990", 'img'=> 'volant/20081113115185_2.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "2010", 'img'=> 'volant/gt_hab10.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "2020", 'img'=> 'volant/1302832116658_U4613P33DT20110414220146.jpg',
        'title'=> '',
        'desc' => ''),
);

$keyimg[5] = 'camera/camera-1988-Digital.jpg';
$data[5] = array (
  array('date' => "1000", 'img'=> 'camera/camera-1000-obscura-around_1000_AD.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1826", 'img'=> 'camera/camera-1826-early_photographic.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1850", 'img'=> 'camera/cameras-1850-plate.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1900", 'img'=> 'camera/camera-1900-Pilm.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1948", 'img'=> 'camera/camera-1948-instant.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1988", 'img'=> 'camera/camera-1988-Digital.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1890", 'img'=> 'camera/camera-1890-late1800s_view.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1990", 'img'=> 'camera/camera-1990-sony_phone.jpg',
        'title'=> '',
        'desc' => ''),
);

$keyimg[6] = 'diodes/Diode-diodeelectroluminescente-1960-SB.jpg';
$data[6] = array (
  array('date' => "1904", 'title'=> 'Diode par John FLEMING',
        'img'=> 'diodes/Diode-1904-SB.jpg',
        'desc' => 'Premier tube à vide.'),
  array('date' => "1907", 'title'=> 'Triode (Lampe) par L. DE FOREST',
        'img'=> 'diodes/Diode-Triode_tube_1906-SB.jpg',
        'desc' => 'Mise au point à partir de la diode de J. FLEMMING, sur laquelle il rajoute une feuille métallique, "l\'audion" qui s\'appellera ensuite "triode" est un amplificateur d\'intensité électrique. La première "lampe" réellement utilisable a été mise au point en France par H. ABRAHAM et utilisée par l\'ensemble des Alliés pendant la première guerre mondiale, d\'où son nom : Lampe TM (pour Télégraphie Militaire).'),
  array('date' => "1937", 'title'=> 'Additionneur binaire à relais par G. STIBITZ',
        'img'=> 'diodes/Diode-additionneurbinaire-1937-SB.jpg',
        'desc' => ''),
  array('date' => "1940", 'title'=> '',
        'img'=> 'diodes/le-circuit-imprime_1940-SB.jpg',
        'desc' => ''),
  array('date' => "1942", 'title'=> 'Diodes au germanium',
        'img'=> 'diodes/Diode-Germanium_Diode_1942-SB.jpg',
        'desc' => 'Le germanium est un semi-conducteur, c\'est à dire que "dopé" par des impuretés, il conduit dans un sens ou dans l\'autre suivant la nature de cette impureté. Par l\'association d\'un morceau de germanium dopé positivement (P) et un morceau dopé négativement (N), on obtient une diode qui ne conduit le courant que dans un seul sens.'),
  array('date' => "1947", 'title'=> 'Le transistor bipolaire à jonction par J. BARDEEN, W. BRATTAIN et W. SCHOCKLEY',
        'img'=> 'diodes/Diode-transistorbipolaire_1947-SB.jpg',
        'desc' => 'Il est constitué d\'une très fine couche P entre deux couches N (ou bien l\'inverse). Lorsque l\'on fait circuler un faible courant entre une couche P et une couche N, un flux d\'électrons entraîne une conduction entre les deux couches de même nature: c\'est l\'effet transistor. Ce composant est à l\'origine d\'une révolution dans l\'électronique, en effet la faible énergie nécessaire pour le faire fonctionner, ainsi que sa petite taille rendent très vite les tubes obsolètes.'),
  array('date' => "1954", 'title'=> 'Transistor au silicium',
        'img'=> 'diodes/Diode-transistorausillicium-1954-SB.jpg',
        'desc' => 'Beaucoup moins cher, plus facile à produire et à utiliser (mais hélas ayant une vitesse de conduction moins élevée) que le germanium, le silicium va devenir le symbole d\'une nouvelle ère.'),
  array('date' => "1959", 'title'=> 'Circuit intégré par Jack KILBY',
        'img'=> 'diodes/Diode-schéma_circuit_intégré-1959-SB.jpg',
        'desc' => 'Fabriquées à l\'aide de semi-conducteurs (sous forme d\'alliage binaire de Phosphure de Gallium et d\' Arséniure de Gallium), ces diodes ont la propriété d\'émettre de la lumière dans le spectre infrarouge ou visible. Leurs principales qualités sont une très faible consommation, une grande rapidité et une durée de vie quasi-illimitée.'),
  array('date' => "1960", 'title'=> 'Diodes Électroluminescentes',
        'img'=> 'diodes/Diode-diodeelectroluminescente-1960-SB.jpg',
        'desc' => 'Fabriquées à l\'aide de semi-conducteurs (sous forme d\'alliage binaire de Phosphure de Gallium et d\' Arséniure de Gallium), ces diodes ont la propriété d\'émettre de la lumière dans le spectre infrarouge ou visible. Leurs principales qualités sont une très faible consommation, une grande rapidité et une durée de vie quasi-illimitée.'),
  array('date' => "1971", 'title'=> 'Le premier microprocesseur: le 4004 d\'Intel',
        'img'=> 'diodes/Processeur-4004intel-1971-Intel-SB.jpg',
        'desc' => 'Il comporte 2300 transistors et exécute 60 000 opérations par seconde à une fréquence de 108 Khz. Sa puissance était égale à celle de l\'ENIAC'),
  array('date' => "1974", 'title'=> 'Carte à puce par Roland MORENO',
        'img'=> 'diodes/Diode-carteapuce-1974-SB.jpg',
        'desc' => ''),
  array('date' => "2001", 'title'=> 'Itanium',
        'img'=> 'diodes/Itanium-2001-SB.jpg',
        'desc' => 'Certes ce n\'est pas le premier processeur 64 bits à sortir mais c\'était certainement un des plus en vue. Conçu par Intel et Hewlett-Packard, il est à la croisé des architectures RISC (HP-PA) et CISC (utilisé par les processeurs Intel). Seulement il n\'a jamais vraiment rencontré de succès.  Intel Itanium Processor'),
  array('date' => "2003", 'title'=> 'Opteron d\'AMD',
        'img'=> 'diodes/Processeur-AMD_Opteron_2003-SB.jpg',
        'desc' => 'Alors que l\'Itanium ne peux exécuter les applications 32 bits que grace à un complexe système d\'émulation, l\'Opteron est le premier microprocesseur capable de supporter des programmes 32 bits et 64 bits à pleine vitesse. L\'Opteron a également un controleur de mémore intégré alors que traditionnellement, celui-ci est séparé. Même si à l\'époque Windows n\'était pas disponible en version 64 bits, le succès de ce processeur est immédiat, en particulier pour des serveurs Linux.'),
);

$keyimg[7] = 'imprimante/4imprimanteHP.jpg';
$data[7] = array (
#array('date' => "", 'img'=> 'imprimante/1dyn003_original_900_1200_.jpg_2671111_b890018c0d2117d9f83ca85dbf7c6f2b.jpg'),
  array('date' => "0", 'img'=> 'imprimante/2a1351-940-thickbox.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "0", 'img'=> 'imprimante/2plume_encrier.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "800", 'img'=> 'imprimante/2qXylographie_8siecle.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1450", 'img'=> 'imprimante/3_Imprimerie_Gutenberg1450.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1990", 'img'=> 'imprimante/5zp_printer_350.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "2000", 'img'=> 'imprimante/4imprimanteHP.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "2007", 'img'=> 'imprimante/4canon_clc_3220.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "2008", 'img'=> 'imprimante/6polaroid_pogo_3_screen_large.jpg',
        'title'=> '',
        'desc' => ''),
);

$keyimg[8] = 'memoire/8-disquemagnétique-1977-Intel-SB.jpg';
$data[8] = array (
  array('date' => "0", 'img'=> 'memoire/1-Pap-VIII_eme_S-Chine-SB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1928", 'img'=> 'memoire/2_Carteperforee80_colonnes-1928-IBM-SB.jpg',
        'title'=> 'Carte perforee',
        'desc' => 'écriture sur papier, le système de perforation est mécanique. Ce système qui deviendra un standard est la généralisation de la carte perforée qui est à l\'origine de la compagnie.'),
  array('date' => "1948", 'img'=> 'memoire/3-memàtubedewilliams-1948-SB.jpg',
        'title'=> '&nbsp;',
        'desc' => 'Développée par F. C. Williams, ce type de mémoire utilise les charges résiduelles laissées sur l\'écran d\'un tube cathodique après qu\'il ait été frappé par le faisceau d\'électron.'),
  array('date' => "1949", 'img'=> 'memoire/4-bandemagnétique1949-SB.jpg',
        'title'=> '',
        'desc' => 'Les bandes magnétiques ont été utilisées comme mémoires de masse dès les débuts de l\'informatique. Dès les années 1950 le format des bandes devient rapidement standard : une bande mesurait au maximum 2 400 pieds de long (732 mètres) pour ½ pouce (12 7 mm) de large ; des bobines plus petites de 200, 300 ou 600 pieds ont aussi été produites'),
  array('date' => "1954", 'img'=> 'memoire/5-memoireatoresferrite-1954-SB.jpg',
        'title'=> '',
        'desc' => 'Pendant une petite vingtaine d\'année, ce principe de mémoire sera le plus utilisé avant d\'être remplacé par la mémoire à semi-conducteurs.'),
  array('date' => "1955", 'img'=> 'memoire/6-tambourmagnétique-1955-SB.jpg',
        'title'=> '',
        'desc' => 'Le tambour possédait une tête de lecture/écriture par piste.<br/>La capacité de stockage par unité de volume était faible mais, par contre, le temps d\'accès moyen était bien plus court que celui des disques durs. De ce fait, les tambours étaient des mémoires de masse de choix pour les systèmes à mémoire virtuelle.'),
  array('date' => "1956", 'img'=> 'memoire/BRL61-IBM_305_RAMAC-1956-SB.jpg',
        'title'=> '',
        'desc' => 'crée par Reynold johnson , le RAMAC 305 (Ramac pour Random Access Method of Accounting and Control), a été dévoilé au public par IBM. La production commerciale commença en juin 1957. Jusqu’en 1961, plus d’un millier d’unités furent vendues. Son prix : 10 000 dollars (de l’époque) par mégaoctet.'),
  array('date' => "1968", 'img'=> 'memoire/7-memoiresemi_conducteur-1968-SB.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1977", 'img'=> 'memoire/8-disquemagnétique-1977-Intel-SB.jpg',
        'title'=> '',
        'desc' => 'le RAMAC 305 (Ramac pour Random Access Method of Accounting and Control), a été dévoilé au public par IBM. La production commerciale commença en juin 1957. Jusqu’en 1961, plus d’un millier d’unités furent vendues. Son prix : 10 000 dollars (de l’époque) par mégaoctet.'),
  array('date' => "1984", 'img'=> 'memoire/9-CDROM-1984-Sonyphillips-SB.jpg',
        'title'=> '',
        'desc' => 'Cédérom en français Version informatique du CD permettant de stocker à la fois du texte, des images, des sons... Sa capacité était exceptionnelle pour l\'époque: 680 Mo.'),
  array('date' => "1985", 'img'=> 'memoire/10-dvd-1985-SB.jpg',
        'title'=> '',
        'desc' => 'Il s\'agit simplement d\'une puce mémoire avec un connecteur USB. L\'ensemble à la taille d\'une clé (et peut d\'ailleurs se mettre en porte-clé) ce qui a donné son nom. Les capacités actuelles dépassent celles d\'un CD-ROM avec l\'avantage d\'être réinscriptible à volonté.'),
  array('date' => "2001", 'img'=> 'memoire/11-cleusb-2001-SB.jpg',
        'title'=> '',
        'desc' => ''),
);

$keyimg[9] = 'navigation/08-Google.Maps.2004-WA.jpg';
$data[9] = array (
  array('date' => "-400", 'img'=> 'navigation/01-Boussole.IVavJC-WA.jpg',
        'title'=> 'Boussole',
        'desc' => 'Une boussole est un instrument de navigation constitué d’une aiguille magnétisée qui s’aligne sur le champ magnétique de la Terre. La boussole est une invention chinoise. '),
  array('date' => "-150", 'img'=> 'navigation/02-Astrolabe.IIavJC-WA.jpg',
        'title'=> 'L\'astrolabe',
        'desc' => 'L\'astrolabe est une représentation plane de la sphère armillaire. Il est construit pour une latitude donnée. Il permet de repérer la position des astres. L\'astrolabe existe depuis l\'Antiquité (IIème sièce avant JC).Il a été conçu par Hipparque. Ptolémée l\'étudia 3 siècle plus tard.'),
  array('date' => "1350", 'img'=> 'navigation/03-Baton.Jacob.XIV-WA.jpg',
        'title'=> 'Bâton de Jacob',
        'desc' => 'Également nommé arbalestrille, ce « bâton » est constitué de 4 marteaux perpendiculaires (ou deux bois un coulissant sur l\'autre par son milieu). Il servait aux astronomes pour mesurer les distances angulaires des étoiles, puis un peu plus tard, il a été utilisé par les navigateurs à mesurer leur position en mer, la latitude exacte mais pas la longitude (puisqu\'ils ne pouvaient embarquer une horloge assez précise).'),
  array('date' => "1675", 'img'=> 'navigation/04-Chronometre.marine.1675-WA.jpg',
        'title'=> 'Chronomètre de marine',
        'desc' => 'Un chronomètre de marine, appelé aussi montre de marine, est une horloge suffisamment précise pour être utilisée comme une base de temps portable, y compris sur un véhicule en mouvement.'),
  array('date' => "1730", 'img'=> 'navigation/05-Sextant.1730-WA.jpg',
        'title'=> 'Le sextant',
        'desc' => 'Instrument est utilisé pour déterminer la position géographique de l\'observateur. Il était particulièrement utilisé pour la navigation. Sa construction repose sur les lois de la réflexion de la lumière. Le sextant a la forme d\'un secteur angulaire de 60°.'),
  array('date' => "1993", 'img'=> 'navigation/06-Instr.electr.nav.XX-WA.jpg',
        'title'=> 'Instruments électroniques de navigation',
        'desc' => 'Sont des instruments qui utilisent un ensemble des techniques et méthodes qui permettent au navire : de déterminer sa position, de calculer la route à suivre pour se rendre à sa destination et que peuvent donner de donnés par rapport à la velocité du vent, humidité et autres. '),
  array('date' => "1995", 'img'=> 'navigation/07-Dispositf.GPS.1995-WA.jpg',
        'title'=> 'Dispositif GPS',
        'desc' => 'Les dispositifs GPS font la Global Positioning System (GPS)qui est un système de géolocalisation fonctionnant au niveau mondial. En 2011, il est avec GLONASS, un système de positionnement par satellites entièrement opérationnel et accessible au grand public.'),
  array('date' => "2004", 'img'=> 'navigation/08-Google.Maps.2004-WA.jpg',
        'title'=> 'Google Maps',
        'desc' => 'Google Maps est un service de cartographie en ligne sur Internet. Ce service permet, à partir de l\'échelle d\'un pays, de pouvoir zoomer jusqu\'à l\'échelle d\'une rue. Le service a été créé par Google.'),
  array('date' => "2005", 'img'=> 'navigation/09-Google.Earth.2005-WA.jpg',
        'title'=> 'Google Earth',
        'desc' => 'Google Earth est un logiciel permettant une visualisation de la Terre avec un assemblage de photographies aériennes ou satellitaires.'),
  array('date' => "2010", 'img'=> 'navigation/10-Instr.Nav.Aerienne.XX-WA.jpg',
        'title'=> 'Instruments de Navigation aérienne',
        'desc' => 'La navigation aérienne est l\'ensemble des techniques permettant à un pilote d\'aéronef de maitriser ses déplacements. En général, cette route débute et se termine sur un aérodrome.'),
);


$keyimg[10] = 'projecteur/Projecteur_LCD-1989-EPSON_VJP-2000-7.jpg';
$data[10] = array (
  array('date' => "0", 'img'=> 'projecteur/Projecteur-leather_shadow_theater3.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1700", 'img'=> 'projecteur/Projecteur-theatre_d\'ombres_chinoises-1.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1600", 'img'=> 'projecteur/Projecteur-theatre_d\'ombres_chinoises-2.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1640", 'img'=> 'projecteur/Projecteur-1640-4.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1900", 'img'=> 'projecteur/Projecteur-trois_attraper-6.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1930", 'img'=> 'projecteur/Projecteur-80_ans_plus-5.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1985", 'img'=> 'projecteur/Projecteur-mov-la_venir.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1989", 'img'=> 'projecteur/Projecteur-3LCD-EPSON-8.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1996", 'img'=> 'projecteur/Projecteur-1996-DLP-9.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1989", 'img'=> 'projecteur/Projecteur_LCD-1989-EPSON_VJP-2000-7.jpg',
        'title'=> '',
        'desc' => ''),
  array('date' => "1999", 'img'=> 'projecteur/Projecteur-1999-LCOS-JVC-8.jpg',
        'title'=> '',
        'desc' => ''),
#array('date' => "1999", 'img'=> 'projecteur/Projecteur-1999-LCOS-JVC-10.jpg'),
);

$keyimg[11] = 'virtual_reality/08-AlphaBino.2005-WA.jpg';
$data[11] = array (
  array('date' => "1850", 'img'=> 'virtual_reality/01-Lunettes.stereoscopiques.1850-WA.jpg',
        'title'=> 'Lunettes stéréoscopiques',
        'desc' => 'La stéréoscopie (du grec stéréo- : solide, -scope : vision) est l\'ensemble des techniques mises en œuvre pour reproduire une perception du relief à partir de deux images planes.'),
  array('date' => "1900", 'img'=> 'virtual_reality/02-Appareil.photo.x_stereoscopiques.1900-WA.jpg',
        'title'=> 'Appereil photo à deux objectifs pour stéréoscopiques',
        'desc' => 'Un appareil stéréoscopique (plus court : appareil stéréo) est un appareil photographique rassemblant deux chambres photographiques - et donc deux objectifs - placés côte à côte de manière solidaire dans un même boîtier, destiné à produire commodément et dans un même instant un couple stéréoscopique, c\'est-à-dire deux photographies jumelles (mais non semblables) en vue de la restitution du relief ou, si l’on préfère, de la 3e dimension.'),
  array('date' => "1950", 'img'=> 'virtual_reality/03-Lunettes.x.anaglyphes.1950-WA.jpg',
        'title'=> 'Lunettes stéréoscopiques pour anaglyphes',
        'desc' => 'Les lunettes stéréoscopiques sont destinées à l\'observation de films, photographies ou autres images stéréoscopiques. Les lunettes bicolores permettent la vision des anaglyphes. Les couleurs des filtres sont toujours complémentaires.'),
  array('date' => "1960", 'img'=> 'virtual_reality/06-Mach.Photogrammetrie.1960-WA.jpg',
        'title'=> 'Machine de photogrammétrie',
        'desc' => 'La machine de photogrammétrie permet d\'effectuer des mesures dans une scène, en utilisant la parallaxe obtenue entre des images acquises selon des points de vue différents. Recopiant la vision stéréoscopique humaine, elle a longtemps exploité celle-ci pour reconstituer le relief de la scène à partir de cette différence de points de vue.'),
  array('date' => "1973", 'img'=> 'virtual_reality/05-Projector.images._hologra.1973-WA.jpg',
        'title'=> 'Projector des images holographies',
        'desc' => 'L\'holographie est un procédé d\'enregistrement de la phase et de l\'amplitude de l\'onde diffractée par un objet. Ce procédé d\'enregistrement permet de restituer ultérieurement une image en trois dimensions de l\'objet. Ceci est réalisé en utilisant les propriétés de la lumière cohérente issue des lasers.'),
  array('date' => "1980", 'img'=> 'virtual_reality/04-Lunettes.occult.alter.1980-WA.jpg',
        'title'=> 'Lunettes à occultations alternées',
        'desc' => 'Elles font appel à la technique des cristaux liquides. Le projecteur ou le téléviseur émet alternativement à une cadence rapide, l\'image destinée à l\'œil droit, puis celle destinée à l\'œil gauche.'),
  array('date' => "2005", 'img'=> 'virtual_reality/07-3ScopeHMD.2005-WA.jpg',
        'title'=> 'Casque de realité virtuel 3Scope HMD',
        'desc' => 'C\'est un casque en forme de lunette SVGA et Champ visuel de 40° diagonale.'),
  array('date' => "2005", 'img'=> 'virtual_reality/08-AlphaBino.2005-WA.jpg',
        'title'=> 'Casque de realité virtuel AlphaBino (Optic-See-Through with alpha channel)',
        'desc' => 'Ce prototype offre la caractéristique unique d\'un procédé optique see through.'),
  array('date' => "2008", 'img'=> 'virtual_reality/09-i-glasses.i3PC.2008-WA.jpg',
        'title'=> 'Casque de realité virtuel i-glasses i3PC',
        'desc' => 'C\'est un casque avec référence du 800x600 comme l\'ecran d\'un ordinateur mais avec champ visuel réduit.  '),
  array('date' => "2010", 'img'=> 'virtual_reality/10-Casque.Cocoon.2010-WA.jpg',
        'title'=> 'Le casque virtual Cocoon',
        'desc' => 'Le dispositif consiste en un très grand écran panoramique Led/LCD, sous une visière pivotante, qui retransmet les images en haute définition, quatre haut-parleurs assurant une ambiance sonore surround ultra-réaliste. La panoplie est complétée par une canule nasale, permettant de diffuser des produits odorants sur commande, un distributeur de saveurs dans la bouche et  des gants haptiques à retour tactile, voir à retour d’effort, pour avoir la sensation de résistance.'),
);
